# Generated by Django 4.2.1 on 2023-05-24 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rol', '0001_initial'),
        ('persona', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persxcurso',
            fields=[
                ('idPersonaXcurso', models.IntegerField(primary_key=True, serialize=False)),
                ('Curso_idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
                ('Persona_Rol_idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
                ('Persona_idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
            options={
                'verbose_name': 'Persona por curso',
                'verbose_name_plural': 'Personas por cursos',
            },
        ),
    ]
