# Generated by Django 4.2.1 on 2023-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personxcurso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persxcurso',
            name='idPersonaXcurso',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
