# Generated by Django 4.2.1 on 2023-05-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personxcurso', '0002_alter_persxcurso_idpersonaxcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persxcurso',
            name='idPersonaXcurso',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
