# Generated by Django 4.2.1 on 2023-05-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personxcurso', '0003_alter_persxcurso_idpersonaxcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='persxcurso',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
