# Generated by Django 4.2.1 on 2023-05-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personxcurso', '0006_alter_persxcurso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persxcurso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
