# Generated by Django 4.2.1 on 2023-05-24 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(blank=True, max_length=32, null=True)),
                ('cedula', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('Rol_idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
