# Generated by Django 4.2.1 on 2023-05-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('duracion', models.DurationField()),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
