# Generated by Django 4.2.1 on 2023-05-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='idCurso',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
